package lawyer.base.ccase.page;

import com.base.page.BasePage;

/**
 * <b>功能：</b>LawCustomerPage<br>
 * <b>作者：</b>dragon<br>
 * <b>日期：</b> 2018-07-12 <br>
 * <b>版权所有：<b>lawyer-helper版权所有(C) 2018，www.lawyer-helper.com<br>
 */
public class LawCustomerPage extends BasePage {
		private java.lang.Integer id;//   客户ID	private java.lang.String code;//   客户编码	private java.lang.String name;//   客户名称	private java.lang.String ctype;//   客户类别	private java.lang.String idCard;//   客户身份证信息	private java.lang.String eCode;//   企业组织机构代码	private java.lang.String phone;//   联系电话	private java.lang.String linkman;//   联系人	private java.lang.String createBy;//   创建者	private java.util.Date createDate;//   创建时间	private java.lang.String updateBy;//   更新者	private java.util.Date updateDate;//   更新时间	private java.lang.String remarks;//   备注信息	private java.lang.String delFlag;//   删除标记	public java.lang.Integer getId() {	    return this.id;	}	public void setId(java.lang.Integer id) {	    this.id=id;	}	public java.lang.String getCode() {	    return this.code;	}	public void setCode(java.lang.String code) {	    this.code=code;	}	public java.lang.String getName() {	    return this.name;	}	public void setName(java.lang.String name) {	    this.name=name;	}	public java.lang.String getCtype() {	    return this.ctype;	}	public void setCtype(java.lang.String ctype) {	    this.ctype=ctype;	}	public java.lang.String getIdCard() {	    return this.idCard;	}	public void setIdCard(java.lang.String idCard) {	    this.idCard=idCard;	}	public java.lang.String getECode() {	    return this.eCode;	}	public void setECode(java.lang.String eCode) {	    this.eCode=eCode;	}	public java.lang.String getPhone() {	    return this.phone;	}	public void setPhone(java.lang.String phone) {	    this.phone=phone;	}	public java.lang.String getLinkman() {	    return this.linkman;	}	public void setLinkman(java.lang.String linkman) {	    this.linkman=linkman;	}	public java.lang.String getCreateBy() {	    return this.createBy;	}	public void setCreateBy(java.lang.String createBy) {	    this.createBy=createBy;	}	public java.util.Date getCreateDate() {	    return this.createDate;	}	public void setCreateDate(java.util.Date createDate) {	    this.createDate=createDate;	}	public java.lang.String getUpdateBy() {	    return this.updateBy;	}	public void setUpdateBy(java.lang.String updateBy) {	    this.updateBy=updateBy;	}	public java.util.Date getUpdateDate() {	    return this.updateDate;	}	public void setUpdateDate(java.util.Date updateDate) {	    this.updateDate=updateDate;	}	public java.lang.String getRemarks() {	    return this.remarks;	}	public void setRemarks(java.lang.String remarks) {	    this.remarks=remarks;	}	public java.lang.String getDelFlag() {	    return this.delFlag;	}	public void setDelFlag(java.lang.String delFlag) {	    this.delFlag=delFlag;	}
}